### ISSUE TITLE
Include Boxbuddy for distrobox management

### ISSUE THREAD

**Issue by bi0shacker001** [ublue-os/bazzite#1022]
### Describe the package

Distrobox is really useful, but I'm a fan of having the option of a gui for simpler management tasks.
The best gui I can find for Distrobox is boxbuddy. Any chance it can be either included, or provided as an option during setup? It's not hard to install, but might be easier to give less knowledgeable people a minimal-setup option for managing applications.

### Image

Desktop

**Comment by wolfyreload** [comment]
i'm not one of the Bazzite devs but I had a look at the source code and it looks like the flatpak of Boxbuddy was added in version 2.4.0 which was released on 14 March 2024. I suspect that the list of flatpaks don't get  reapplied on every upgrade (as this would cause flatpaks that you explicitly uninstalled to get reinstalled). 

Here is a link to the commit that added Boxbuddy https://github.com/ublue-os/bazzite/pull/797/commits

**Comment by nicknamenamenick** [comment]
Yeah this has been part of Bazzite since February.  If you do not have this installed, it can easily be installed via Flatpak, but give us an output of your `rpm-ostree status`,  and did you rebase from Fedora Silverblue/Kinoite since we do not include Flatpaks without an additional `ujust` command for that.
