### ISSUE TITLE
Not able to format an SD Card on SteamDeck since 3.0.0 

### ISSUE THREAD

**Issue by Brunvik** [ublue-os/bazzite#1034]
### Describe the bug

When trying to format an SD Card in Gamemode on SteamDeck you'll instantly get an error message

Trying to format via disk utility ends in getting stuck on the formating process

I am on deck-gnome 

### What did you expect to happen?

After starting the formating process having it successfully finishing and mounting the SD-Card

### Hardware

SteamDeck LCD 256GB

**Comment by nethunter** [comment]
Happens to me too, can confirm on Asus ROG Ally.

**Comment by fehbari** [comment]
Same problem on Legion Go, unable to format in game scope. I'm able to format from KDE disk utility, but then back to game mode the SD card doesn't show up as a storage location.

**Comment by tedonporter** [comment]
I am also having this issue. Just installed 3.0.1 Gnome version today on my Legion Go. When trying to format under game mode it says:

"We encountered an error while formatting your microSD card (2). Please try again or contact Steam support.

I tried manually formatting it in desktop mode to BTRFS and once back in gaming mode it now shows up under storage devices but has a yellow caution notice and says it needs to be formatted. Pressing the format button just fails with another error.

**Comment by fehbari** [comment]
> I am also having this issue. Just installed 3.0.1 Gnome version today on my Legion Go. When trying to format under game mode it says:
> 
> "We encountered an error while formatting your microSD card (2). Please try again or contact Steam support.
> 
> I tried manually formatting it in desktop mode to BTRFS and once back in gaming mode it now shows up under storage devices but has a yellow caution notice and says it needs to be formatted. Pressing the format button just fails with another error.

This is going to sound very silly, but have you retried physically removing and reinserting the SD card when that happens?

I've been using mine just fine after formatting in desktop mode, then today I started getting the yellow icon as if it was unformatted. Removing and reinserting the SD card made it go away and the Steam library I had in the SD card was recognized again.

That said, there's definitely something off in Bazzite 3.0 with SD cards on the Legion Go. Hope it can be addressed soon.

**Comment by Traumlewis** [comment]
I have the same problem on my St

> I can confirm the same behaviour on my SteamDeck LCD with 512GB w/ deck-gnome. The error message reads: FORMAT ERROR. Failed to format.
> 
> Formatting the sd with btrfs on my laptop works, but the sd isn't recognized in Gaming Mo

> I can confirm the same behaviour on my SteamDeck LCD with 512GB w/ deck-gnome. The error message reads: FORMAT ERROR. Failed to format.
> 
> Formatting the sd with btrfs on my laptop works, but the sd isn't recognized in Gaming Mode.

I have the same problem on my Steam Deck😞

**Comment by vagrantwinds** [comment]
Also having the same problem on my Steam Deck where SD Cards will not format in the Steam GUI. The card itself works fine and will format just fine under KDE Partition Manager, GParted booted from a USB stick, etc.

**Comment by usafballer** [comment]
Joined just to add this.  Can't get format to work on my Legion Go with Bazzite 3.0.1 installed.  I put the SD card into my Steam Deck and formatted that way and it works in the LeGo now.

**Comment by arongkatz** [comment]
Joined just for this...yesterday I was able to use the micro SD card by formatting it on my steam deck but emudeck just wouldn't recognize it...today I tried it again by formatting on steam deck but now I cannot format it or use it in game mode anymore

**Comment by theblu3j** [comment]
Also have this issue. Steam Deck 64GB upgraded to 512GB, on the deck image with Plasma. Can't format under System tab, can't format under storage tab. Formatting with KDE Partition Manager (feels like it takes longer on Bazzite than on my EndeavourOS system and previously under SteamOS) I can't add the drive as a Steam Drive in Desktop mode.

**Comment by D1Ck3n** [comment]
I have the same issue with an HTPC. i cant format the drives from Gamemode :(

**Comment by Jack32X** [comment]
Same issue, ROG Ally, this needs to be addressed as it is breaking emudeck installs

**Comment by Miles0511** [comment]
Joined here to report same issue with my legion go installed with bazzite OS 3.1. Cant reformat on desktop nor game mode. Is there already a solution to this?

**Comment by Miles0511** [comment]
Update: Not 100% sure if this is what fixed the issue since coincidentally, a software update was released just now at the same time I tried this work around. 

Workaround 
1. Flashed my SD card using Balenaetcher with Bazzite OS  (same process when creating an image for ur bootable drive) 
2. Insert SD Card to device
3. Reformat in game mode (no message that it went through successfully or even an error message)
4. Restart device

**Comment by Dizzy611** [comment]
Just chiming in to report this is definitely still a thing. Or at least, my card does seem to have formatted from game mode but Game mode itself doesn't think it's formatted. I was trying to reformat it because I had an issue with it getting stuck while trying to update games I'd had on the Deck before installing Bazzite. Regardless, what I had to do was add the microSD card manually as a storage location in Steam from desktop mode, and it seems to have started working since then?

**Comment by connertron** [comment]
Does mounting the sd card from desktop mode then downloading game in desktop mode to sd card work when you go back into game mode?

**Comment by thexavier666** [comment]
Hi, I have fixed it by referring to this youtube video (https://www.youtube.com/watch?v=f9skT5eYhPU). To summarize what he did

1. Switch to Desktop mode
2. Open KDE partition manager
3. Unmount the SD card
4. Delete all partitions of the SD card
5. Format the SD card and make sure it has permissions for everyone (visible in GUI)
6. Apply the formatting and exit the KDE partition manager (Do not switch to Gamemode)
7. Create the directory `sudo mkdir /var/mnt/steam/steamlibrary`
8. Give it the correct ownership `sudo chown bazzite:bazzite /var/mnt/steam/steamlibrary`
9. Give it all exec permissions `chmod 777 /var/mnt/steam/steamlibrary`
10. Open KDE partition manager. Make sure SD card is unmounted
11. Right click SD card and select "Edit Mount Point"
12. In Path, enter "/var/mnt/steam/steamlibrary". Apply and exit
13. Reboot and enter Desktop mode
14. Open steam (Desktop version)
15. Go to Steam -> Settings -> Storage
16. Click Home -> Add Drive. Your SD card should be visible.
17. Move any game, preferably small, to the SD card
18. Exit to Gamemode

Now it should be working.

Note: If you are using Asus ROG Ally, ensure that your SD card reader has not burnt out due to the heating issue.
