### ISSUE TITLE
[Installer] Freeze on Dracut Issue

### ISSUE THREAD

**Issue by manoliptram** [ublue-os/bazzite#109]
I've been trying to use the online installer to get Bazzite GNOME working on my steam deck. I got on my network and the installer started, but it freezes on the following screen:

![20230806_121109](https://github.com/ublue-os/bazzite/assets/25092054/1a118207-185b-4a78-b17d-973b705ef1fa)

Can someone help me out here? I don't have a lot of experience with Dracut so I don't know how to fix this.

**Comment by EyeCantCU** [comment]
This usually happens when writing the ISO with Ventoy or when rd.live.check hangs. I would try removing rd.live.check as a kernel argument. To do that, press E on the boot entry, go down the line using the arrow keys that begins with linux and remove rd.live.check. Save the configuration by pressing the Ctrl key and X at the same time.

You could also try writing it again with Fedora Media Writer and see if that works out. Let me know if any of this helps

**Comment by Juggalo187** [comment]
I have the same problem, I tried removing rd.live.check and using Fedora Media Writer instead of Rufus but to no avail.

**Comment by nicknamenamenick** [comment]
I had a similar issue, just a black screen with no error message.  This may work for you because it worked for me. Install stock Fedora Kinoite - https://fedoraproject.org/kinoite/download/ and flash it your flash drive or whatever bootable medium you have.  Installation should be quite similar to Bazzite

_This next part can be found on the README near the bottom of each variant of Bazzite._

Then when you install stock Fedora Kinoite, open Konsole and enter: 

**for Desktop w/ an AMD/Intel GPU**
`podman pull ghcr.io/ublue-os/config && rpm-ostree install --assumeyes --apply-live --force-replacefiles $(find ~/.local/share/containers -name ublue-os-signing.noarch.rpm 2>/dev/null) && rpm-ostree rebase --uninstall $(rpm -q ublue-os-signing-* --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{Arch}') ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:latest`

**for Desktop w/ a Nvidia GPU**
`podman pull ghcr.io/ublue-os/config && rpm-ostree install --assumeyes --apply-live --force-replacefiles $(find ~/.local/share/containers -name ublue-os-signing.noarch.rpm 2>/dev/null) && rpm-ostree rebase --uninstall $(rpm -q ublue-os-signing-* --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{Arch}') ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest`

**for Steam Deck**
`podman pull ghcr.io/ublue-os/config && rpm-ostree install --assumeyes --apply-live --force-replacefiles $(find ~/.local/share/containers -name ublue-os-signing.noarch.rpm 2>/dev/null) && rpm-ostree rebase --uninstall $(rpm -q ublue-os-signing-* --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{Arch}') ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest`

and so on.. for GNOME variants, just copy from the github README here: 
![image](https://github.com/ublue-os/bazzite/assets/121328689/5f4d348c-6e4d-451f-8cc3-8a26da5b630b)

Then reboot when it has finished.  This will rebase you from stock Fedora Kinoite to Bazzite.  

**NOTE: If you plan to try this method with the Steam Deck, keep in mind the installer will not scale well on the Deck screen!  You will have to press the tab key on your physical keyboard to try and continue it, usually located on the bottom right of the screen which gets cut off with this method.**

**Comment by Labsdj** [comment]
i put my video now public to view the error message

**Comment by rodnheli** [comment]
Had also installation issues with ventoy and fedora media writer.
With latest rufus (4.0.2025) installation worked.

**Comment by shuriken1812** [comment]
This issue does not seem to be bazzite specific, my own custom image which is based on silverblue main also has this issue https://github.com/shuriken1812/ShurikenOS

**Comment by spoelstraethan** [comment]
I just ran into this issue but resolved it using the exact same install media by switching out the docking station/hub I was using for one that didn't have any memory card readers in it. I'm wondering if installing from microSD (common for the Steam Deck because the reader is built in) whether the internal reader which is often /dev/sda or /dev/mmcblk0 might get bumped if an external dock also has a reader and the switch from boot selection to kernel loading doesn't pass an explicit block device UUID to install from?

**Comment by juicypop** [comment]
It might sound discouraging but keep trying different USB drives and image writers.
After I think 15+ attempts, I finally created a working USB drive with Rufus 4.34 I think, latest official release. And what should I say, finally it let me pass above screen within a few seconds without further workarounds. 
For reference, I'm running quite aged hardware in a htpc. i5 3470s with a 750ti on an Asus p8h61-i Mainboard. I disabled secure boot prior to all my attempts.

Hope this helps someone.

**Comment by beforan** [comment]
> After I think 15+ attempts, I finally created a working USB drive with Rufus 4.34 I think, latest official release.

Do you recall what options you used in Rufus when it worked? MBR/GPT? ISO or DD?

**Comment by juicypop** [comment]
> Do you recall what options you used in Rufus when it worked? MBR/GPT? ISO or DD?
Sure, it was my last attempt trying default settings. This means MBR/ISO.
 
If this should still fail, i was going about to try:
- GPT/ISO
- MBR/DD
- GPT/DD

When choosing one of the nvidia options, go for the 2nd entry with basic driver support.
My aged hardware produced graphical glitches all over my monitor i couldn't even see what i was doing there

**Comment by noelmiller** [comment]
We are currently in the process of regenerating this ISO. It is not complete yet. If you want more information, please follow this issue: https://github.com/ublue-os/main/issues/468

**Comment by KyleGospo** [comment]
We now have a new offline installer that can be downloaded at https://bazzite.gg/#image-picker

Let us know if you have any issues with the new one :)
