### ISSUE TITLE
On nvidia optimus systems, an Xorg instance is started and forced onto the dgpu

### ISSUE THREAD

**Issue by qoijjj** [ublue-os/bazzite#1253]
### Describe the bug

1. Rebase to bazzite-nvidia
2. Start the system and login
3. run `nvidia-smi`
4. observe that Xorg is running on the dgpu

### What did you expect to happen?

1. Rebase to kinoite-nvidia
2. Start the system and login
3. run `nvidia-smi`
4. observe that nothing is running on the dgpu

### Output of `rpm-ostree status`

```shell
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:376ffb04e940fce1390027c1ffa65662e8521d209dc7f5fbd1bc4ba3c235f718
                  Version: 40.20240619.0 (2024-06-20T01:06:19Z)
```

**Comment by petete1** [comment]
This is the expected behavior on nvidia prime. Not a bug.

**Comment by qoijjj** [comment]
@petete1 So you're saying that KDE/Kinoite has a bug then? This only occurs on Bazzite, not Kinoite.

**Comment by petete1** [comment]
AFAIK Kinoite doesn't include the proprietary nvidia drivers.

**Comment by qoijjj** [comment]
@petete1 I'm talking about ublue's kinoite-nvidia image. It doesn't have this issue.

**Comment by petete1** [comment]
I just did a quick test on kinoite-nvidia, and it's true that Xorg isn't running. Now tried bazzite-nvidia:testing and it's the same. Looks like the new 555 driver changed things and there's no Xorg process on the dGPU anymore. So, nothing to fix, you only have to wait for the new driver to get into bazzite.

For the record, that Xorg process has been there since nvidia implemented prime gpu-offloading, that's why I took it for normal.

**Comment by qoijjj** [comment]
> you only have to wait for the new driver to get into bazzite.

@petete1 that's good to hear!

> For the record, that Xorg process has been there since nvidia implemented prime gpu-offloading, that's why I took it for normal.

it happens on gnome and other DEs too, but I don't think it's supposed to on a wayland session unless an application specifically needs an xorg session and it needs that session running on the dgpu.
