### ISSUE TITLE
Trying to connect to Steam Deck running Bazzite 3.5.0 with Steam Link it doesn't show any video in desktop mode

### ISSUE THREAD

**Issue by aboutafter** [ublue-os/bazzite#1304]
### Describe the bug

Trying to connect from my PC running bazzite:stable to the Steam Deck running bazzite-deck:stable with the Steam Link flatpak, it doesn't show any video (it works if the SD is on Gaming Mode). 

I can use the application if I have the SD by my side looking at its screen. So, it connects, but it doesn't show anything on my PC. 

Previously, using the same PC with the same Steam Link Flatpak, I could use the application correctly when the Steam Deck was running SteamOS. 

Maybe it's related to the fact that the desktop session is running on Wayland on bazzite-deck vs X11 on SteamOS?

### What did you expect to happen?

I expected to use Steam Link with both video and controls on the SD while on the desktop. 

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
Version: 40.20240630.0 (2024-06-30T20:42:59Z)
```

### Hardware

Galileo

**Comment by tristann21** [comment]
> with the Steam Link flatpak

That's strange.. I thought the steam link flatpak was for _connecting_ not _hosting_. What I thought you're supposed to do is setup steam link in the steam app itself for the host, and then use the steam link flatpak to connect. Maybe that's why it only works when you're in game mode? because steam is open? 

If you still haven't gotten it to work, have you considered trying sunshine?

`ujust setup-sunshine`

**Comment by aboutafter** [comment]
I'm running the Steam Link application on my desktop PC (running Bazzite too), not on the Deck. 

I did try Sunshine, but the screen was rotated to the right and I couldn't find a way to fix that.
