### ISSUE TITLE
Can't use System update - invalid signature when validating ASN.1 encoded signature

### ISSUE THREAD

**Issue by k9janer** [ublue-os/bazzite#1316]
### Describe the bug

Hello,

I installed the nvidia KDE version of bazzite just 2 days ago. Today I wanted to update to the most recent release, but unfortunately, I keep getting the following error:

Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: cryptographic signature verification failed: invalid signature when validating ASN.1 encoded signature
System update failed: 
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

### What did you expect to happen?

I expected the System updater to work fine, just like 2 days ago.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:43a94e8b18644ac34a9c5e6f1611915c576bfe08f70504e4f602d58f2bd11312
                  Version: 40.20240625.0 (2024-06-27T02:08:13Z)
          LayeredPackages: dnf-plugins-core

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:43a94e8b18644ac34a9c5e6f1611915c576bfe08f70504e4f602d58f2bd11312
                  Version: 40.20240625.0 (2024-06-27T02:08:13Z)
```

### Hardware

AMD Ryzen 5 7600
Nvidia GeForce RTX 4070 Super
32 GB Ram
AsRock B650M-HDV/M.2 with latest firmware

**Comment by castrojo** [comment]
We're aware of the issue and are working on a fix, will post as soon as we have more information, thanks!

**Comment by p5** [comment]
We made some mistakes yesterday which caused OS updates to break.

Please can you follow the instructions in [this Discourse post](https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689) to remediate the issues.

TL;DR
We lost access to our signing keys so had to rotate them.
Users need to run the following command or manually perform the actions in [this script](https://github.com/ublue-os/config/blob/5c4144d38a2a61e44ca704ffdf2d50bbcb9ff7ed/scripts/fix-key-and-update.sh)

```
$ curl -sL https://fix.universal-blue.org/ | sudo bash 
```

Apologies for the inconvenience caused by this!  We are making changes to processes so that it doesn't happen again.
