### ISSUE TITLE
Unable to install on steam deck

### ISSUE THREAD

**Issue by Kirit29** [ublue-os/bazzite#134]
![16917256690108594994178376435851](https://github.com/ublue-os/bazzite/assets/15988336/f18353be-6f40-4709-abb5-3ddda7b26a0e)

Trying to install the bazzite deck image and keep getting greeted by this error.

**Comment by Kirit29** [comment]
Figured out the problem

**Comment by Kirit29** [comment]
Now I keep booting into emergency mode whenever I try installing it to an empty partition on my steamdeck. I'm trying to dual boot steam os and bazzite

**Comment by szescxz** [comment]
> I'm trying to dual boot steam os and bazzite

That's the problem. `systemd-gpt-auto-generator` is attempting to mount SteamOS' home partition at `/home` in Bazzite, which will cause conflict because Bazzite has one at `/var/home`.

As a workaround (or the solution?), you'll need to disable it in emergency shell and reboot:
```
# ln -s /dev/null /etc/systemd/system-generators/systemd-gpt-auto-generator
```

Not going to blame Bazzite/Universal Blue since [they did mention that dual boot is not supported](https://universal-blue.org/installation/).

**Comment by KyleGospo** [comment]
Windows only, recommendation is to install windows first and then install Bazzite in the remaining space.
