### ISSUE TITLE
Weird washed out colours in GNOME affecting 1 screen in a triple monitor setup

### ISSUE THREAD

**Issue by speakradmin** [ublue-os/bazzite#1347]
### Describe the bug

Kind of hard to explain but the colours seem washed out or have too much white/grey tint. It's definitely not a brightness setting or a colour profile. It seems to only affect one of the 2 Dell monitors I have. Initially it affected my second monitor but now it's moved to the first and the second one is fine.

### What did you expect to happen?

Brightness/Saturation was normal until a few weeks back

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:7674e78f608cc90d152e74610d1cac9ad5ba896eb2aed6941d67e4f068b9a984
                  Version: 40.20240707.0 (2024-07-08T01:18:32Z)
          LayeredPackages: sunshine

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:34717b5e0862ae1d242402807ba5b0ce7907f83e840cf6603840e489c9457a93
                  Version: 40.20240706.0 (2024-07-06T07:24:58Z)
          LayeredPackages: sunshine
```

### Hardware

MSI MAG B550M MORTAR MAX
AMD 5800X
AMD RX 5900 XT
2 x Dell G3223D 165hz monitors DP
1 x Hisense U7k 4k TV 120hz HDMI

### Extra information or context

I have 2 Dell G3223D Monitors and a 4K TV hooked up to my PC. I'm not sure it has anything to do with the fact that I'm running triple monitor because when I plug everything else out except the affected monitor the issue persists. Oddly, it started a couple weeks back but resolved itself after a reboot. I have updated the monitor firmware to the latest using a Windows machine.

I've tried factory resetting the monitors, deleting colour profiles, disabling VRR on the monitors, setting lower refresh rates and resolutions, nothing changes the washed out look of the image. I've even moved the affected monitor to a different port on my graphics card and it's still the same. I plugged my laptop into the affected screen and it's fine.

Any advice for debugging?

**Comment by DreamingCuttlefish** [comment]
May be related to #1230

**Comment by jankais3r** [comment]
Check that you don't have HDR enabled.

**Comment by speakradmin** [comment]
> May be related to #1230

Doubtful as that bug seemed to be related to software brightness control which my monitors don't have. Nevertheless I tried to see if I could get the output of

`cat /sys/class/backlight/amdgpu_bl1/{brightness,actual_brightness}`

But that didn't work because, since I don't have a software controllable backlight, there's nothing under /sys/class/backlight/

> Check that you don't have HDR enabled.

Yep it's definately turned off on each monitor itself. Interestingly, I recall a few months back, HDR started "working" in the Gnome session but curiously only on one monitor. At that point I still had HDR enabled on the monitors. It didn't look very much like what I'm experiencing now but the white balance was definately way off and everything looked terrible. I tried messing with a few settings but ultimately disabled HDR on the monitors as I figured it was still early days for HDR in the Gnome session.

**Comment by speakradmin** [comment]
Yay seems to be fixed in today's update!

```
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:c53a8b7cdb78233b3b13f58a6f770b18a0abb8f6f283e9cf4cf33d3c8f552a74
                  Version: 40.20240712.0 (2024-07-12T04:58:14Z)
          LayeredPackages: sunshine

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:7674e78f608cc90d152e74610d1cac9ad5ba896eb2aed6941d67e4f068b9a984
                  Version: 40.20240707.0 (2024-07-08T01:18:32Z)
          LayeredPackages: sunshine
```

**Comment by speakradmin** [comment]
Aaaand it's back. This time only one monitor.

rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:6dc8c4c0779253561b2c57b28fd71f6efa08a09c64e06f8fac5456fbd71d81a5
                  Version: 41.20241211 (2024-12-11T07:30:41Z)
          LayeredPackages: sunshine
            LocalPackages: lact-libadwaita-0.6.0-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:a1e956b154de68c2c15909630c8209d7255e583d4c32e36618ec8b0cdf5b9017
                  Version: 41.20241210 (2024-12-10T08:52:57Z)
          LayeredPackages: sunshine
            LocalPackages: lact-libadwaita-0.6.0-0.x86_64

**Comment by speakradmin** [comment]
Tried swapping cables and the issue moved to the other monitor so I figured it was a bad cable. Rebooted and it then back to the original monitor.

Then I tried a live USB of Fedora 41 and the issue is gone. Tried swapping cables there multiple time figuring it was an interference/display negotiation issue but I could not recreate it.

Anyhow, since this issue is now closed, I doubt anyone will look at this and give me some guidance on how to troubleshoot. Ah the joys of opensource community driven projects!

**Comment by rekordskratch** [comment]
This issue is back but this time I have more info that might help diagnose things.

I am now running the latest Bazzite deck gnome 44
`State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:ada96e69f4cf670b5fe2b597bacb86afd57c8866393f6807a5c0b8a2a974bf96
                  Version: 44.20260825 (2026-08-25T23:01:11Z)
          LayeredPackages: sunshine

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:ada96e69f4cf670b5fe2b597bacb86afd57c8866393f6807a5c0b8a2a974bf96
                  Version: 44.20260825 (2026-08-25T23:01:11Z)
`

I have since changed monitors to a single wide screen but I can say even with the previous monitors and on Bazzite 43, the same exact symtoms and workarounds applied.

So this time it's an AMD 9070 XT with a AOC Agon AG493UCX2 49" ultra-wide.

Here are the symptoms...fresh install of Bazzite 44 (Well using the latest iso which is still based on 43 but the install process updates you to 44 and boots straight into game mode)
Everything in game mode works perfectly (aside form the current known issues)
If I switch to desktop I get extremely washed out colours... blacks are grey etc. Before you ask, it's NOT HDR. I have that disabled in the monitor settings and gnome display settings shows it's disabled...remember this is a fresh install.
Even if I enable HDR and try mess around with different HDR modes, refresh rates, colour profiles...nothing changes the extremely washed out look.

Now for the weird part....
When I was still on 43 I accidently discovered that if I start a Sunshine stream from my phone or tablet (Moonlight, pretty default settings) and then use that to switch to desktop...boom the issue is gone. I was baffled...rebooted a bunch of times, tried switching to desktop with controller/keyboard, only one monitor connected etc etc. Same reporducable behaviour every time!

So this time on a fresh 44 install, I saw the same washed out colours and thought....it can't be! New kernel version, new DE version, new gamescope, mesa etc etc! So I thought let me try the Sunshine workaround...after initially struggling to get [Sunshine working](https://docs.bazzite.gg/Advanced/sunshine/#setting-up-sunshine-on-deck-images) I eventually went with the community maintained stable package (Thanks pvermeer!) and tried again. And boom! It works. No more washed out colours...but _only_ if I enter game mode with Sunshine, and exit to desktop!

Anyway, if anyone is interested in helping me troubleshoot this, please let me know!

Some side notes, I suspect this is at least partially related to these issues. Mostly because the workaround to get the overlay to appear is to "move the mouse" with your touchscreen and then guess what? The Sunshine stream of Steam game mode appears exactly the same kind of washed out as the gnome desktop does!
https://github.com/ublue-os/bazzite/issues/1276
https://github.com/LizardByte/Sunshine/issues/3860#issuecomment-2954267416
