### ISSUE TITLE
Volume is considerably lower than on Windows (Ally X)

### ISSUE THREAD

**Issue by salmaninay** [ublue-os/bazzite#1481]
### Describe the bug

The speakers sound quieter than they should, even at 100% volume. 

### What did you expect to happen?

I expected to have the same volume as on Windows.

### Output of `rpm-ostree status`

```shell
AllyX@pc-215:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:0030210b0396e99ff0b5e0b60e265181314f1c60398b045225ee76626d8e1dbf
                  Version: 40.20240809.0 (2024-08-09T05:12:26Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:fa9d7c77f4be2d451aa62cc232649afd087a2ea0f539df891ef4bb5cb6ac488a
                  Version: 40.20240807.0 (2024-08-07T07:32:24Z)
```

### Extra information or context

ROG Ally X RC72LA_RC72LA

**Comment by RodoMa92** [comment]
Probably a DSP issue? Might have to take a look at their drivers if they have a specific DSP. Can you post a dmesg bootup log to see if it is loading the default DSP firmware instead of the specific Ally X one?

**Comment by KyleGospo** [comment]
We don't have a Ally X DSP, only the original Ally. One will need to be made by someone with the hardware necessary.

**Comment by RodoMa92** [comment]
Don't they have a cirrus DSP like the previous boards? The audio driver for Windows should have the file.

**Comment by KyleGospo** [comment]
> Don't they have a cirrus DSP like the previous ally? The audio driver for Windows should have the file.
> 
> I don't have the hardware, so I can't really tell if they have or not.

That's functional, if it wasn't there would be no audio. We are also using their firmware. What were left with is settings, such as a software equalizer.

**Comment by MurderFromMars** [comment]
I applied the legion go experimental sound fix to my ally x and it improved the loud ess considerably. Tried sharing this on reddit but everyone had a fit because it's not designed for the ally. (Obviously) But it did solve this issue for me. With no noticeable impact on sound quality.  Might want to consider using it at least until they get some official support for the ally x. It's easy to uninstall

**Comment by doomsdalicious** [comment]
Another thing I have noticed and found a fix for on Reddit is if the volume level is lower than 100% in desktop mode, it will be much lower in gaming mode. The fix for me was to go into desktop mode and turn the volume to 100%, and then return to game mode and the volume was much louder. There is even a button you can check to make it go past 100%, but I never tried that. After the fix, I still don't think it's as loud as it was on Windows, but it's much louder than it was and very usable. I do wonder if I checked the box to go past 100% if that would fix it, but it's plenty loud for me and I don't want to break my Ally speakers.

https://www.reddit.com/r/LinuxOnAlly/comments/1e240uy/volume_seems_too_low_on_bazzite/

**Comment by MurderFromMars** [comment]
> Another thing I have noticed and found a fix for on Reddit is if the volume level is lower than 100% in desktop mode, it will be much lower in gaming mode. The fix for me was to go into desktop mode and turn the volume to 100%, and then return to game mode and the volume was much louder. There is even a button you can check to make it go past 100%, but I never tried that. After the fix, I still don't think it's as loud as it was on Windows, but it's much louder than it was and very usable. I do wonder if I checked the box to go past 100% if that would fix it, but it's plenty loud for me and I don't want to break my Ally speakers.
> 
> https://www.reddit.com/r/LinuxOnAlly/comments/1e240uy/volume_seems_too_low_on_bazzite/

I've tried this. It works great until you have to adjust the volume in game mode for whatever reason. Then it seems to revert to standard volume. At least in my case.

**Comment by salmaninay** [comment]
The Legion Go experimental fix worked ! Thank you !

**Comment by MurderFromMars** [comment]
> The Legion Go experimental fix worked ! Thank you !

No worries. 

Just a caveat to keep in mind here is the legion go sound fix does break audio output over HDMI, meaning if you try to dock the ally x with this fix enabled it won't output sound to your TV. 

This can be worked around with headphones which will work properly, 

Alternatively, there is a decky loader plug in you can use to boost volume at will while in game mode. (Allows you to access the 150 percent volume in game mode).  This fix may be preferable if you dock the ally x regularly.
