### ISSUE TITLE
Deck images cannot keep power up/suspending animations after reboot

### ISSUE THREAD

**Issue by Zeglius** [ublue-os/bazzite#1487]
### Describe the bug

Seems animations settings arent preserved, bazzite workaround overrides them when starting steam in a deck image.

### What did you expect to happen?

Bazzite default animations should be applied once, not every time steam client is started.

### Extra information or context

Bug introduced with commit 373a73da8232589cb7cf57d4e0fd5764d67d5142.
https://github.com/ublue-os/bazzite/blob/6a65be86f42a3d750324f063fa67a665a35d4e76/system_files/desktop/shared/usr/bin/bazzite-steam#L18-L29

**Comment by MiraiSubject** [comment]
This issue is still relevant. It actually also ruins the AnimationChanger plugin DeckyLoader because it overwrites the downloaded boot animation inside the plugin's downloaded folder.

**Comment by Gadg8eer** [comment]
> This issue is still relevant. It actually also ruins the AnimationChanger plugin in DeckyLoader because it overwrites the downloaded boot animation inside the plugin's downloaded folder. 

Confirmed on my OneXFly 7840U.

**Comment by kevbenjam** [comment]
@KyleGospo the issue appears on my SteamDeck as well when using the AnimationChanger plugin in DeckyLoader. Do you have any idea how the code could be fixed, so that Bazzite doesn't overwrite the downloaded animations with its own animations when using the plugin?

**Comment by kevbenjam** [comment]
@KyleGospo the issue appears on my SteamDeck as well when using [SDH-AnimationChanger](https://github.com/TheLogicMaster/SDH-AnimationChanger) via [Decky Loader](https://github.com/SteamDeckHomebrew/decky-loader). Do you have any idea how the code could be fixed, so that Bazzite doesn't overwrite the downloaded animations with its own animations when using the mentioned plugin?
