### ISSUE TITLE
Disabling steam input turns the setting page blank Ally X

### ISSUE THREAD

**Issue by 522122** [ublue-os/bazzite#1496]
### Describe the bug

I started having issues with controller on battle.net game so I tried to disable steam input in Controller Settings per game.
The page turned blank and I can no longer change controller settings for this game. Re-adding it to the library seems to reset it.
Same behavior in desktop or big picture mode.

### What did you expect to happen?

I expect when I change a setting to try it out to be able to easily change it again.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:6ce12036986eb6b37658dac3d335ce826106cf46a628516be96bf966bc8f6cbf
                  Version: v3.6-40.20240809.0 (2024-08-09T21:14:34Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:6ce12036986eb6b37658dac3d335ce826106cf46a628516be96bf966bc8f6cbf
                  Version: v3.6-40.20240809.0 (2024-08-09T21:14:34Z)
```

### Hardware

ROG Ally X RC72LA_RC72LA

**Comment by HikariKnight** [comment]
This is a steam issue so not something we can fix, only seen it happen if steam has issues properly communicating with the external controllers (re-plugging the controller will fix it in that case).

However since this is a handheld
if you are permanently stuck however with a blank settings page then reset steam with
`ujust fix-reset-steam`

this will remove all of steams files except files we know we do not need to remove for a reset, and then force you to log in again.
