### ISSUE TITLE
Shouldn't Steam be installed on the '-desktop' image too?

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/bazzite#15]
I guess it would be better for it to be installed by default on the desktop image because it allows for compatibility with programs like EmuDeck / DeckyLoader

**Comment by KyleGospo** [comment]
"bazzite" contains Steam for compatibility reasons (Mainly because using Steam for gamescope-session via Distrobox would be difficult.

"bazzite-desktop" specifically forgoes that because, when it reaches 1.0, it'll have an install script that sets up bazzite-arch in distrobox OOTB with Steam ready to go through that.

**Comment by KyleGospo** [comment]
FYI this is now complete on the current images, expect a 1.0 release quite soon.
