### ISSUE TITLE
Many bugs (No signal, Broken Decky, Game Mode reset)

### ISSUE THREAD

**Issue by DavidRLTG** [ublue-os/bazzite#1501]
### Describe the bug

1. Even after updating to the latest version successfully, Bazzite has a weird bug where if I start up the deck docked, A weird gray background three dot loading screen will show up on the deck, and the TV will not receive signal once it loads.
2. Decky loader breaks constantly after reinstalling bazzite. After a while, plugins refuse to work correctly, updating them fails, installing new plugins fails, not even uninstalling plugins goes well. I tried wiping and reinstalling decky, didnt fix it.
3. Steam Game Mode constantly resets itself, forgets my settings, turns off HDR, and makes me log in again each time.
4. Sometimes, once I return to game mode, Returning to desktop again is not possible, it simply reloads gamemode.

### What did you expect to happen?

Well, I simply expected everything mentioned to work properly, and not break..

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:6ce12036986eb6b37658dac3d335ce826106cf46a628516be96bf966bc8f6cbf
                  Version: v3.6-40.20240809.0 (2024-08-09T21:14:34Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:fa9d7c77f4be2d451aa62cc232649afd087a2ea0f539df891ef4bb5cb6ac488a
                  Version: 40.20240807.0 (2024-08-07T07:32:24Z)
```

### Hardware

`jupiter`, Steam Deck LCD 256GB.

**Comment by HikariKnight** [comment]
1. no idea why this happens, i have the same on my main pc (plymouth shows a grey screen with 3 dots), but i never have had it cause any issues, i think this is caused by something else and you should try pressing ESC during this screen and see what actually happens (or enable ssh and connect from a separate machine to the deck and grab a `journalctl -b 0 |fpaste` and post here along with the output of `sudo dmesg | fpaste`)

2. if you are on steam beta client, do not use decky as it is prone to crash then.
3. this happens when steam crashes, it resets its settings and makes you log in again
4. see `3.`

for 2-3 i would recommend trying `ujust fix-reset-steam` this will reset the steam client to a fresh state, see if it keeps having the issue after that.

for `1.` we wont know anything until we have logs

**Comment by DavidRLTG** [comment]
> 1. no idea why this happens, i have the same on my main pc (plymouth shows a grey screen with 3 dots), but i never have had it cause any issues, i think this is caused by something else and you should try pressing ESC during this screen and see what actually happens (or enable ssh and connect from a separate machine to the deck and grab a `journalctl -b 0 |fpaste` and post here along with the output of `sudo dmesg | fpaste`)
> 2. if you are on steam beta client, do not use decky as it is prone to crash then.
> 3. this happens when steam crashes, it resets its settings and makes you log in again
> 4. see `3.`
> 
> for 2-3 i would recommend trying `ujust fix-reset-steam` this will reset the steam client to a fresh state, see if it keeps having the issue after that.
> 
> for `1.` we wont know anything until we have logs

For the 1st issue, here are photos, if it helps (Sorry for the bad shot)
![AGC_20240829_113812589](https://github.com/user-attachments/assets/91e2e280-5701-430f-890f-cc6b9d678af3)
![AGC_20240829_113818952](https://github.com/user-attachments/assets/7331ddcb-48eb-40f1-b7f6-a9e479a5cd47)
