### ISSUE TITLE
Charging got really slow after install "dual boot" bazzite Legion Go

### ISSUE THREAD

**Issue by MriLLest** [ublue-os/bazzite#1524]
### Describe the bug

After install, charging went from 10-100% around 1hr and 30ish minutes to 4hrs as it is only pulling 5w of charging in when docked or plugged in with Original 65w charger and 140w power bank. 

### What did you expect to happen?

please find out how to get back my original speed for charging without having to change the bios charging from slow to medium as this was not the case prior to install. Thanks guys, love your work and keep on keeping on as I'm loving Bazzite!

**Comment by Statix1337** [comment]
Ran into this too on a Legion Go 2 (Bazzite) — traced it to the kernel's UCSI driver timing out talking to the EC over USB-C (`ucsi_acpi ... GET_CONNECTOR_STATUS failed (-110)`), which escalates into full ACPI/EC comms failures under load. A kernel-arg workaround (`acpi.ec_delay`/`acpi.ec_polling_guard`) fixed the stutter for me. Full writeup in case it's the same root cause: #5260
