### ISSUE TITLE
Winetricks cannot be updated on Bazzite

### ISSUE THREAD

**Issue by ticklemyIP** [ublue-os/bazzite#1563]
### Describe the bug

I have been trying to update winetricks on my Bazzite system, however it is not possible because of the OS' immutable nature. I have been trying to use sudo, root (sudo winetricks --self-update) but got error `warning: You don't have the proper permissions to run this command. Try again with sudo or as root.`. As wine (winetricks) comes with the OS in addition with Lutris and other component it would be great if this worked. I also haven't seen anyone  else mention this issue on any other immutable or atomic distro issue tracker which is weird. My system is basically vanilla btw.

### What did you expect to happen?

I can update winetricks.

### Extra information or context

I have opened a **RELEVANT ISSUE** over at winetricks: https://github.com/Winetricks/winetricks/issues/2257

**Comment by KyleGospo** [comment]
This is by design, you're using an atomic operating system so your usr folder is read only.

We are using the package made by the fedora project for this, if you need a newer one I would suggest you run it locally or use a flatpak if available, but the one included in the image should be functional.
