### ISSUE TITLE
Add Pantheon Desktop

### ISSUE THREAD

**Issue by Bassobr** [ublue-os/bazzite#1781]
### Describe the package

As a short preface: I am not a software developer and therefore cannot assess at all how valid and feasible my request is.

I mainly work with macOS and have tried various Linux desktop systems from time to time (Gnome, KDE, Cinnamon, Pantheon, etc.). In the end, I always end up with Elementary OS's Pantheon desktop, which in my opinion is very consistent and simple in design and operation.

Would it be possible to build another Bazzite flavor based on the Pantheon desktop?

I have seen that there is already a Silverblue variant with Pantheon desktop (https://github.com/sodaliterocks/sodalite) and maybe there are synergies here.

### Image

Desktop

**Comment by HikariKnight** [comment]
Adding a new DE is a big endeavor and adds more maintenance burden.
For a DE to be even considered it has to at minimum support
* Wayland
* HDR
* VRR
* All of the above have to be in a stable release
* Someone with knowledge of the DE has to be willing to help maintain it

For now Budgie is on the list and is grandfathered in due to being planned before HDR existed on linux.
Cosmic is also on the list (for now) once it has a stable release due to vested interest from both users and devs.

**Comment by Bassobr** [comment]
Thank you very much for the clarification.
