### ISSUE TITLE
Cannot connect to Displaylink docking station after upgrade to Bazzite 41

### ISSUE THREAD

**Issue by KarinnoAmp** [ublue-os/bazzite#1801]
### Describe the bug

When I upgrade my ROG Ally to Bazzite 41, I cannot connect to my Displaylink docking station while running in both KDE Plasma and steam deck menu. As checking with other machine it can connected normally.

### What did you expect to happen?

I expected my ROG Ally with Bazzite 41 should connect to Displaylink docking station or any that use Displaylink standard.

### Output of `rpm-ostree status`

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:1bfd10804de25620056818e9d6647891beda97c4fd58e165b77755441188e6bb
                  Version: 41.20241029 (2024-10-29T03:47:13Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:1bfd10804de25620056818e9d6647891beda97c4fd58e165b77755441188e6bb
                  Version: 41.20241029 (2024-10-29T03:47:13Z)

### Hardware

ROG Ally RC71L_RC71L

**Comment by noelmiller** [comment]
There seems to be an issue upstream with the package itself in Negativo. In order to get the release out on time, we had to remove the kernel mod from our akmods. I am hopeful that this will be addressed soon as I also have a device that requires the displaylink driver to work properly. 

You can track progress on the issue here: https://github.com/ublue-os/akmods/issues/248

**Comment by noelmiller** [comment]
@KarinnoAmp This has been merged into the main branch and should be available. I just tested it and it is working properly!
