### ISSUE TITLE
request package: crontab

### ISSUE THREAD

**Issue by duhow** [ublue-os/bazzite#1870]
### Describe the package

`crontab` is not available and I cannot define scheduled tasks (eg. mute my system at midnight).

📦 Requesting package `cronie`.

### Image

Desktop

**Comment by HikariKnight** [comment]
use [systemd timers](https://opensource.com/article/20/7/systemd-timers).
place the .timer and .service files into `/etc/systemd/system/` or `/etc/systemd/user/` instead of the `/usr/lib/systemd`  folders the article talks about, the systemd documentation says to use `/etc/systemd`, `/usr/lib/systemd` is meant for system/distro vendors while `/etc/systemd` is for end users to use.

**Comment by duhow** [comment]
![Image](https://github.com/user-attachments/assets/9f524a9b-5f3d-49b1-bbec-b926096ac803)

KDE Task scheduler won't work because `crontab` command is not available.

**Comment by HikariKnight** [comment]
Hmm we should be 1:1 with fedora kinoite, i will check if it is also missing from upstream

For now you can just layer crontab with `rpm-ostree install crontab` however if an update later includes it (the update will error out and it will not be applied), you will have to `rpm-ostree remove crontab` and reboot before updating :)

**Comment by HikariKnight** [comment]
@duhow i did some investigating and kcron (the task scheduler package for kde) is not even used upstream anymore and is included by accident in our kinoite images.

It is probably going to be replaced by `systemdgenie` in the future, but kcron and crontabs are no longer used upstream.
kcron has now been removed going forward in our main images, meaning the task scheduler section of systemsettings will vanish in a future update.

To restore the functionality if you want to keep it once that update lands please layer both `crontabs` and `kcron`
`rpm-ostree kcron crontabs`
