### ISSUE TITLE
Signature verification error

### ISSUE THREAD

**Issue by Lux-pogu** [ublue-os/bazzite#189]
Trying to install the bazzite deck and have reflashed,redownloaded,used different usbs,for this image,and they all have (during the install) the error “ostree container image deploy —sysroot=/mnt/sysimage —image=ghcr.io 
/ublue-os/bazzite-deck:38 —no-signature-verification’ exited with the code 1”. pulling my hair out over this.

**Comment by nagaame** [comment]
I have the same error.🥲

**Comment by akdev1l** [comment]
It’s not a signature verification error - this happens when anything goes wrong during `ostree container image deploy` during installation (could be I/O error or network error or anything) 

anaconda doesn’t retry or do anything but crash… 

I’ll see if I can find some time to file a bug upstream. There’s not really much the ublue project can do here sadly. 

The error also doesn’t depend on the image, the iso is just an installer but the actual OS image is downloaded from GitHub container registry every time - it looks like it fails in many cases

**Comment by nagaame** [comment]
I would like to know if there is a way to collect or view logs during the installation process.

**Comment by akdev1l** [comment]
> I would like to know if there is a way to collect or view logs during the installation process.

https://docs.fedoraproject.org/en-US/quick-docs/anaconda/anaconda_logging/#_logging_on_the_installed_system

**Comment by szescxz** [comment]
Leaving a note for anyone from China who has this issue: yes, you need a VPN (preferably on your router) or a GHCR mirror.
To specify a mirror you need to edit the boot option at the GRUB menu. Ventoy users who are using [my workaround](https://github.com/ublue-os/bazzite/issues/144#issuecomment-1679901732) can also `nano /tmp/ks-urls.txt` before running `anaconda`.

**Comment by KyleGospo** [comment]
> Leaving a note for anyone from China who has this issue: yes, you need a VPN (preferably on your router) or a GHCR mirror.
> To specify a mirror you need to edit the boot option at the GRUB menu. Ventoy users who are using [my workaround](https://github.com/ublue-os/bazzite/issues/144#issuecomment-1679901732) can also `nano /tmp/ks-urls.txt` before running `anaconda`.
> 
> You can always `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/<YOUR VARIANT HERE>:<VERSION_HERE>` after installation if you have trust issues with mirrors.

If there's another git service that you're able to access with similar functionality, let me know and I'll be happy to fork this over there.

**Comment by Elcapone86** [comment]
The error comes from the wifi encryption. I tried it over the eGpu via Lan and the installation went through without problems. Uses a Lan connection or temporarily removes the Wlan encryption.

**Comment by kubepy** [comment]
Hi, @Lux-pogu 

I tried to modify and create a offline installation iso from the origin iso to support `offline installation` and logged the steps.
it may install sucessfully after  you build your own offline iso.

[https://github.com/kubepy/bazzite-deck-offline](https://github.com/kubepy/bazzite-deck-offline)

**Comment by Lux-pogu** [comment]
would love to do this,but don't have arch. is there anyway you could send me the built iso? if not that's okay,but i think if you can't,i'm just gonna give up on bazzite. no matter what i do it just doesn't work for me

**Comment by szescxz** [comment]
> If there's another git service that you're able to access with similar functionality, let me know and I'll be happy to fork this over there.

I think the point is not Git but container registries - we are pulling the container image for the installation, not the source code. And I'm not seeing much container registries offering mirror service here (most of the public ones only mirror Docker Hub).
To solve this in the long-term I think a server/object storage/CDN is needed to serve static files - either for the offline installer above, or put the container image into an OSTree repository and pull with `ostree-remote-image` (so people who want to mirror it doesn't have to run a registry, a simple HTTP server serving static content is enough).
In the short-term I still prefer offline installer, like adapting isogenerator to something that users can fork the repository and run the GitHub actions themselves, then extract the ISO from the build artifact (since GitHub release doesn't allow anything more than 2 GiB).

> The error comes from the wifi encryption.

Ah yes, I forgot to mention this. The Wi-Fi driver comes with the installer seems buggy. I'm also seeing Wi-Fi speed goes down to just ~128 KiB/s if the driver don't get loaded properly even in an installed system (though it's probably just me broke something which caused that).
If anyone doesn't have an Ethernet cable but has an Android phone then I'd also suggest using USB tethering as well.

**Comment by castrojo** [comment]
https://github.com/ublue-os/isogenerator/pull/81 for the ISO work.

**Comment by castrojo** [comment]
If an online install is too troublesome due to intermittent network issues we recommend using the Fedora installer and then rebasing to it. Here are the instructions: https://universal-blue.org/images/#preparing-to-rebase

**Comment by Lux-pogu** [comment]
> If an online install is too troublesome due to intermittent network issues we recommend using the Fedora installer and then rebasing to it. Here are the instructions: https://universal-blue.org/images/#preparing-to-rebase

would love to do this,but i figured out,i can't install any ostree fedora image.

**Comment by Lux-pogu** [comment]
SOLVED! I AM SO HAPPY TO BE DONE WITH THIS. 

i followed this video https://youtu.be/DIp4yqIe8O4?si=LC8UoIZH5NYOLROu ,for anyone else following it, "/" and "/home" can be whatever size you desire...well,not *any* size but still. i do recommend a swap of at least 8gb,although,i believe 4gb is minimum. good luck to anyone else doing this!

**Comment by Lux-pogu** [comment]
> SOLVED! I AM SO HAPPY TO BE DONE WITH THIS. 
> 
> i followed this video https://youtu.be/DIp4yqIe8O4?si=LC8UoIZH5NYOLROu ,for anyone else following it, "/" and "/home" can be whatever size you desire...well,not *any* size but still. i do recommend a swap of at least 8gb,although,i believe 4gb is minimum. good luck to anyone else doing this!

also, @nagaame ,if you'd like to try this

**Comment by nagaame** [comment]
> > SOLVED! I AM SO HAPPY TO BE DONE WITH THIS.
> > i followed this video https://youtu.be/DIp4yqIe8O4?si=LC8UoIZH5NYOLROu ,for anyone else following it, "/" and "/home" can be whatever size you desire...well,not _any_ size but still. i do recommend a swap of at least 8gb,although,i believe 4gb is minimum. good luck to anyone else doing this!
> 
> also, @nagaame ,if you'd like to try this. also,i did this on silverblue,then rebased with what one of the other comments said. i never tried doing bazzite from the start with this though

thank you everyone, i'll try it

**Comment by noelmiller** [comment]
We are currently in the process of regenerating this ISO. It is not complete yet. If you want more information, please follow this issue: https://github.com/ublue-os/main/issues/468

**Comment by KyleGospo** [comment]
We now have a new offline installer that can be downloaded at https://bazzite.gg/#image-picker

Let us know if you have any issues with the new one :)

**Comment by shanoor** [comment]
I had the same error even while being offline. In my case, the issue was because of already existing uefi boot entries for Fedora and Bazzite. I deleted both and even deleted the Fedora folder from rhe EFI partition and it solved the issue.

I used DiskGenius, it's included in Hirens BootCD or can be installed on Windows. There are probably linux tools for doing the same thing.
