### ISSUE TITLE
Very strange issues since F41

### ISSUE THREAD

**Issue by Guusggg** [ublue-os/bazzite#1907]
Hi,

I realize this is not really a technical bug report, so please forgive me for this. The issues that I'm encountering are just weird to me, and I'm unable to start diagnosing properly so I resort to just telling the symptoms.

Currently I'm using a Acer laptop with Nvidia card. I have been really happily using Bazzite for a year I think, and never encountered issues and was really enthusiastic about Bazzite since it's so rock solid. 

Lately though, and it started happening since the update to F41, I've been having strange issues. I'm sorry that I'm unable to give logs or anything, because the issues are really strange. What I mean is, I would give logs but I'm unable to start figuring out what causes these strange things.

Stuff like:
- Applications not responding
- The applications not responding, freezing my OS
- When the laptop is put to sleep, the laptop starts booting but there's only a black screen **but my mouse is visible and usable.** (I try to go into terminal 2 by CTRL+ALT+F1/F2/F3 or CTRL+ALT+1/2/3 but this doesn't work.)
- After sleep, logging in is impossible; I have a login windows showing up, but when I input my password, nothing happens. Buttons respond to input (hover and click changes the button graphics). After 30 seconds, it tells me "Unlocking failed". 
- Unable to launch my terminal; Plasma reacts and shows the "loading" cursor, then after 1 minute, I get a system notification that the app "launch-terminal" did not respond.
- Applications randomly shutting down; no indication, just windows disappears. When checking system monitor, process is gone.

The issues were so strange that I figured, maybe my hard drive is dieing. The SMART status says it's working as expected however. 

I figured I'd wait a bit and keep daily updating so that maybe my issues would be resolved, however I'm a bit fed up at the moment so I rebased to `stable-40` for now. I don't mean to sound pissed off and I can't overstate how much I like Bazzite.

```
$ bazzite-rollback-helper current
State: idle
AutomaticUpdates: disabled
BootedDeployment:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable (index: 0)
                   Digest: sha256:ce0e694f9eea2efb69baca2753e9b3f8c953b4b5bcb745ad17351350dab32392
                  Version: 41.20241112.1 (2024-11-12T23:59:00Z)
               BaseCommit: eabe0ae3a0eb507e0dd299c6ac287ab62cfda4853c9fe4768b8596ee922ec295
                   Commit: aef613c3e7abcc00e8256d6c117190cf709914d5d6f78a92454cae7984d3ac01
                           ├─ copr:copr.fedorainfracloud.org:matte-schwartz:sunshine (2024-08-12T15:47:19Z)
                           ├─ copr:copr.fedorainfracloud.org:rodoma92:kde-cdemu-manager (2024-10-29T12:13:12Z)
                           ├─ copr:copr.fedorainfracloud.org:rodoma92:rmlint (2024-10-29T12:31:09Z)
                           ├─ copr:copr.fedorainfracloud.org:rok:cdemu (2024-10-21T13:15:21Z)
                           ├─ fedora (2024-10-25T08:41:19Z)
                           ├─ updates (2024-11-16T02:10:14Z)
                           └─ updates-archive (2024-11-16T03:09:46Z)
                   Staged: no
                StateRoot: default
          LayeredPackages: dnf-plugins-core guestfs-tools libvirt-daemon-config-network libvirt-daemon-kvm
                           podman-compose python3-libguestfs qemu-kvm virt-install virt-manager virt-top
                           virt-viewer
```

Is there anything I can do to make this more technical? Pointers to start diagnosing my issues? If anything comes to mind, please let me know. I would like to be on latest stable, but for now I get too annoyed by constantly force-powering my PC off, but I also don't only wanna complain, I'd like to help to resolve issues I (and maybe others) might encounter.

Thank you very much for this project, I'm a huge fan! Please, if there's anything I can do to contribute, I'll try (just about) anything to get more information.

**Comment by atimeofday** [comment]
Hi, do you still have this issue? 

'Rollback and/or rebase and wait' is a valid and correct workaround for a broken update. Sometimes it takes up to a few weeks for the latest update to fix whatever the issue is, especially with Nvidia hardware. The great thing about Bazzite / Atomic is that you can rebase back to a working image until then.

That does look like a relatively large number of layered packages, albeit ones which may need to be layered. Each one adds a degree of uncertainty to updates. If you can do so without breaking anything important, it may be worth pinning your working image, then performing an `rpm-ostree reset` to remove all layered packages from a new deployment, rebasing that new deployment to F41, then testing whether the updated image with nothing layered works properly, then perhaps chasing down which exact package may be causing problems, if any.

To check another hunch, were you using X11 or Wayland on F40? F41 is Wayland-only, which is now mostly-there but a semi-random assortment of Nvidia hardware/firmware/etc can still have issues.

Also, having Nvidia hardware myself (16xx/20xx+), I was informed by maintainers a while back that I should rebase to `bazzite-(gnome-)nvidia-open` since the non-open drivers are now somewhat legacy-only. For right now it may or may not make a difference.
