### ISSUE TITLE
Massive Memory Leak in Harvestella

### ISSUE THREAD

**Issue by RadicalR** [ublue-os/bazzite#198]
Upon starting a new game or loading an existing save, the RAM usage increases until it hits 14 gigs, at which point the game either crashes, or more commonly the Deck crashes. This happens within 10 seconds. 

I've tried it with the Bazzite and Legacy memory options, I've tried both the GE and regular Proton. 

The game worked correctly on SteamOS.

**Comment by nicknamenamenick** [comment]
Attach a game log by entering `PROTON_LOG=1 %command%` in the game's launch options.  It may indicate what the issue is.

**Comment by RadicalR** [comment]
Here you go. 
[steam-1816300.zip](https://github.com/ublue-os/bazzite/files/12449478/steam-1816300.zip)

**Comment by coatlessali** [comment]
Also occurs in Sonic Forces. Crashes in under 30 seconds.

**Comment by RadicalR** [comment]
Can you grab a log and contribute it? Maybe there is a common thread?

**Comment by coatlessali** [comment]
Unfortunately I cannot at this time, as I've reinstalled SteamOS due to a pinch situation and I haven't had time to reinstall Bazzite. The game would freeze with audio on older Proton versions, and on newer Proton versions would freeze the entire system. Legacy swap did nothing to help, and the game uses D3D11/DXVK.

A question I do have is whether or not `PROTON_USE_WINED3D=1` would help. I'll come back to it when I can.

**Comment by RadicalR** [comment]
There is no change if I put PROTON_USE_WIND3D=1 in the launch command.

**Comment by coatlessali** [comment]
`WINED3D` and not `WIND3D`?

**Comment by RadicalR** [comment]
Corrected my typo. But yes, I've doubled checked the entry it was WINED3D.

**Comment by KyleGospo** [comment]
Mesa 23.1.6 had a memory leak that affected Unreal Engine titles. We now ship 23.1.7 which has a fix for that issue. Harvestella in particular wasn't mentioned but it's UE, so it's worth a re-test.
