### ISSUE TITLE
❗ If you've had Bazzite since before September 22nd and never ran "rpm-ostree update", then do it

### ISSUE THREAD

**Issue by h7io** [ublue-os/bazzite#382]
My `rpm-ostree status` was stuck at:
```
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:38
                   Digest: sha256:ebbfd73a6cf40c1b1f29da31b98cc6d69127786f1789726756c8672af384b012
                  Version: 38.20230922.0 (2023-09-22T22:28:15Z)
```

i.e. it was stuck at a week-old version despite the automatic system-updater running. People at Discord said that there was an issue needing a manual `rpm-ostree update` execution. 

Someone else, please fill in the details.

**Comment by gerblesh** [comment]
thank you, here's more detail:
basically `ublue-update` (the auto update program for bazzite) gained a new feature that's able to auto rebase/sign images. Using data from the `/usr/share/ublue-os/image-info.json`, the problem was that there was a typo in the initial implementation (the `image-ref` variable in JSON didn't have the proper prefix), which meant that when `ublue-update` would try to auto sign the image, it was unable to do so, and the system update script would error out. Thus, the system is not able to update. It was later fixed, however it went unnoticed for long enough for some people on the image to be affected. running `rpm-ostree update` manually will solve the issue

**Comment by stunlocked1** [comment]
I just installed bazzite so do I need to do this is was that fixes

**Comment by KyleGospo** [comment]
You do not
