### ISSUE TITLE
Have a bazzite image for Kepler Nvidia GPU with a 470 driver tag

### ISSUE THREAD

**Issue by yodatak** [ublue-os/bazzite#391]
Hello I want to use bazzite with old recycled GPU and I wan to use the Nvidia 470 driver latest that support Kepler GPU
Is there already an image to try?

Thznks a lot

**Comment by hikaricore** [comment]
I would be interested in finding out if such an image exists as well. Pulling the main branch doesn't seem to permit the proper installation of xorg-x11-drv-nvidia-470xx + akmod-nvidia-470xx, nor does the nvidia branch which appears to be static with the latest nvidia driver packages. Attempting to install or replace on either of these builds either fails due to package conflict or installation/compilation errors.

38-470 images are fairly common in other project images as seen here: https://universal-blue.org/images/

Thanks in advance for any insight. :)

**Comment by arthurlutz** [comment]
Interested in this too. Has anyone succeeded in having bazzite work with the nouveau open source driver ?

**Comment by arthurlutz** [comment]
I'm running bazzite with the nouveau driver. Does anyone know how I add nvidia-470xx on an existing system ? (sorry newbie on ublue-os)
