### ISSUE TITLE
Shader cache compiling on game start

### ISSUE THREAD

**Issue by cchrkk** [ublue-os/bazzite#472]
Hello, thanks for this amazing OS. ♥

I have this problem: when I launch a game on my Steam Deck, it compiles the shaders for like 20-25 minutes and If I skip the shader compilation, I get massive lags and game is unplayable.

I'm trying to understand if it's an issue with Steam/with GE-Proton/Bazzite/ or just some setting. And eventually what log to give you :)

Thanks

**Comment by beefchimi** [comment]
I _believe there is a setting_ in Steam to always skip the pre-compile step _(instead of doing it manually each time)_. But as you mentioned, you may experience stutters while in-game because the shaders are then compiling as you play.

It is an unfortunate reality of PC gaming. Even on my brand new gaming rig, I sometimes have to wait forever for shaders to compile _(all the while fans are at full speed)_.

I did find this Reddit thread that indicates there could be a way to speed this up:
https://www.reddit.com/r/linux_gaming/comments/1270813/how_to_speed_up_linux_background_shader/

I have not tried this myself, but I intend to look into it. Launching Counter-Strike 2 takes so long, by the time its ready, I don't even feel like playing anymore 😆

**Comment by cchrkk** [comment]
>It is an unfortunate reality of PC gaming. Even on my brand new gaming rig, I sometimes have to wait forever for shaders to compile (all the while fans are at full speed).

Well, mostly on linux and windows in some games only (first to cross my mind is Warzone/new COD games).

> I did find this Reddit thread that indicates there could be a way to speed this up:
> https://www.reddit.com/r/linux_gaming/comments/1270813/how_to_speed_up_linux_background_shader/

Mmh, I remember reading this option on my gaming pc, I should try to enable it on the deck (maybe in desktop mode if not available in gamescope) and see if it works.


> Launching Counter-Strike 2 takes so long, by the time its ready, I don't even feel like playing anymore 😆

I really hope you're talking about your new gaming rig because you must hate yourself to play cs on the steam deck :D


By the way this behavior didn't occur on the official SteamOS, in there i've never read "Compiling shaders" before running a game, it downloaded a ton of shaders every day for any game in the library, but never compiled by itself. 🤔

**Comment by KyleGospo** [comment]
This is normal steam behavior, you can skip this step thanks to GPL largely rendering this as uneeded.

**Comment by cchrkk** [comment]
On steam os it's not like this, sure I can skip it but runs poorly.

Il ven 27 ott 2023, 01:06 Kyle Gospodnetich ***@***.***> ha
scritto:

**Comment by unicornsandcandies** [comment]
> This is normal steam behavior, you can skip this step thanks to GPL largely rendering this as uneeded.
> 
> We aren't using the same version of Mesa as SteamOS, so there aren't ready made caches provided by Steam. My understanding is that'll improve as we get more users due to how Steam's cache sharing system works.
> 
> Background shader compilation uses a lot of CPU. In the interest of battery life I would keep it off.

If I turn it on, how does it work?

Does it work in the background even when I'm playing some game already? Does it turn stop when launching a game?

And how often is it needed? Only once for every game?

I think I could pay the price of battery usage if this is only once for a game and let's me use my deck normally. Especially that it's really slow on bazzite. I get that it should take some time, but on bazzite it's super slow.

Also,
If it's possible - could you please explain why there's such a big difference? You said something about the way steam precache works. How does it work?

**Comment by EyeCantCU** [comment]
Shaders will be compiled in the background every single time a game is installed or an update is available. It will do this at all times. I certainly wouldn't recommend enabling this. It does take time if you wait it out, and that's the same for almost any system configuration out there unfortunately.

Steam OS downloads precompiled shaders, and they can do this since it targets one hardware configuration on one platform with a single version of mesa. So you never see this as a result of that. However, on all other Linux distros and hardware configurations, shaders have to be compiled before the game runs unless things match Steam OS exactly. But typically, you can skip this and still be fine. I haven't really noticed performance degradation in doing so

**Comment by cchrkk** [comment]
> But typically, you can skip this and still be fine. I haven't really noticed performance degradation in doing so
@EyeCantCU 
Hello, I didn't play on my steam deck much recently. Today I've tried to play some 3d games (everything works just fine with lightweight 2D scrollers) and it's absolutely unplayable. Then I thought about your reply, and I must be missing something huge. This time it didn't compile anything on start, looks like I have 3,5GB of shader cache but OW2 in this example runs at 5-12fps (on menu and same happens ingame).

Here is a video of how bad it looks:
https://imgur.com/GBtTxEm
is it normal?

**Comment by cchrkk** [comment]
> try enabling background shader processing

It was enabled already and the other day I had steam open on desktop mode for 3 hours, what else should I check?
