### ISSUE TITLE
How to dual boot with windows laptop?

### ISSUE THREAD

**Issue by xt234** [ublue-os/bazzite#484]
im trying to setup a dual boot so it doesnt wipe my windows partition but i dont want to use another drive just for bazite.

**Comment by JaCh0o** [comment]
I'm also interested in this, currently my set-up:
Miniforum Hx99g with Ryzen 9 6900hx (with igpu) and Radeon rx6600m 16gb DDR5 and two drives inside:
1tb - windows 11 pro
2tb - chimeraOS 

Because chimeraOS doesn't support secure boot I'm interested in jumping into bazzite (as far as I found is supports secure boot)
May i ask for any instructions to install bazzite on 2 TB drives to maintain windows 11 on second drive and to have fast (2-3 sec) grub window with auto select of bazzite gamepad mode and option to select windows 11 in it ? 
I'm worried about installation of fedora how not to mess up with efi partitions... (Or rather how to do it properly)

**Comment by noelmiller** [comment]
Please review this [documentation](https://universal-blue.discourse.group/docs?topic=129) and attempt the process in there. If you have any issues, please reopen the issue!
