### ISSUE TITLE
Steam Deck Not Updating Flatpaks (Possibly Not Getting Any Updates)

### ISSUE THREAD

**Issue by KaiserCalm** [ublue-os/bazzite#498]
Recently I opened Software Centre and noticed that there were flatpak packages that needed updating. I ran `just update` and got a fleek error, so I removed fleek and nix as detailed in this [issue](https://github.com/ublue-os/bazzite/issues/366#issuecomment-1736301423), as I wasn't really using them anyways, but running `just update` shows that everything is up to date, but the Flatpak packages aren't and I don't think I have the latest rpm-ostree updates either. Running rpm-ostree shows that everything is up to date and ublue-update does not show any errors. Is there anything I can do to solve this? (I have run rpm-ostree after the September 21st update.)

**Comment by KaiserCalm** [comment]
I've also noticed something among the lines of `[FAILED] cec onpower` or something like that when the deck is shutting down. I don't know if it's related.

**Comment by EyeCantCU** [comment]
Everything gets updated through ublue-update in game mode, including Flatpaks, after you press the apply update button. Has it been a bit since you've done this last? Also, if you'd like more granular control over Flatpak updates there's a nice extension in the Decky store called "AutoFlatpaks" I'd suggest checking out. `rpm-ostree` is telling the truth, you're on the latest update

**Comment by KaiserCalm** [comment]
Thank you! I was wondering if I can use that extension after I switched from SteamOS. Good to know that everything is okey.
