### ISSUE TITLE
not an issue. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [ublue-os/bazzite#508]
will this get made for legion go handheld?

**Comment by KyleGospo** [comment]
![20231104_113726.jpg](https://github.com/ublue-os/bazzite/assets/10704358/773e61eb-1962-40ce-b991-41063d68c6d9)

**Comment by DOOMMARINE117** [comment]
> ![20231104_113726.jpg](https://user-images.githubusercontent.com/10704358/280497447-773e61eb-1962-40ce-b991-41063d68c6d9.jpg)
> 
> Use bazzite-deck:39 for now, next build should substantially improve the experience. No extra button support yet.

cool, so things are slowly egtting to work. how to install it?

**Comment by nicknamenamenick** [comment]
> > ![20231104_113726.jpg](https://user-images.githubusercontent.com/10704358/280497447-773e61eb-1962-40ce-b991-41063d68c6d9.jpg)
> > Use bazzite-deck:39 for now, next build should substantially improve the experience. No extra button support yet.
> 
> cool, so things are slowly getting to work. how to install it?

Wait until Tuesday for the Fedora 39 builds to drop and have a smoother experience, but if you want to try it early and test it yourself:  
- Install Bazzite on it normally then once you reach the desktop, open the terminal and enter:
`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39`   
- Keep in mind you should rebase back to `:latest` after Tuesday because the `:39` branch will not be upgraded to 40 when that comes out in 6 months, so to do that enter in the terminal:
`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest`

Please refer to the [installation guide](https://universal-blue.org/images/bazzite/installation/) on how to install Bazzite properly.

**Comment by DOOMMARINE117** [comment]
> > > ![20231104_113726.jpg](https://user-images.githubusercontent.com/10704358/280497447-773e61eb-1962-40ce-b991-41063d68c6d9.jpg)
> > > Use bazzite-deck:39 for now, next build should substantially improve the experience. No extra button support yet.
> > 
> > 
> > cool, so things are slowly getting to work. how to install it?
> 
> Wait until Tuesday for the Fedora 39 builds to drop and have a smoother experience, but if you want to try it early and test it yourself:
> 
> * Install Bazzite on it normally then once you reach the desktop, open the terminal and enter:
>   `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39`
> * Keep in mind you should rebase back to `:latest` after Tuesday because the `:39` branch will not be upgraded to 40 when that comes out in 6 months, so to do that enter in the terminal:
>   `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest`
> 
> Please refer to the [installation guide](https://universal-blue.org/images/bazzite/installation/) on how to install Bazzite properly.

so its comign early. i wait for that one then. awhile im still looking for a distro to run on legion.
