### ISSUE TITLE
[Q]how to uninstall lutris?

### ISSUE THREAD

**Issue by DarkenLX** [ublue-os/bazzite#557]
hi um how would i uninstall lutris im getting a 256 error trying to install epic game store im thinking lutris is buggered somewhere and possibly a clean install of it may fix it.. running bazzite-deck:latest
ive tried rpm -ev lutris 
errors: 
error: can't create transaction lock on /usr/share/rpm/.rpm.lock (Read-only file system)

tried rpm-ostree uninstall lutris:
error: Package/capability 'lutris' is not currently requested

so um how can i do this?

**Comment by KyleGospo** [comment]
It's part of the image, you cannot uninstall it and even if you could you'd be in exactly the same place. If there's an issue it affects everyone or is in a file local to your install that a reinstall would not clear.

**Comment by DarkenLX** [comment]
Ok... So is it something that i should contact lutris support about or open a new issue here? Im not sure if lutris support deals with built-in installs or if they will tell me to contact distro support. Im guessing they will probably tell me to come back here.

**Comment by DarkenLX** [comment]
> It's part of the image, you cannot uninstall it and even if you could you'd be in exactly the same place upon reinstall. If there's an issue it affects everyone or is in a file local to your install that a reinstall would not clear.

Ok... So is the issue with lutris something that i should contact lutris support about or open a new issue here? Im not sure if lutris support deals with built-in installs or if they will tell me to contact distro support. Im guessing they will probably tell me to come back here.

**Comment by bi0shacker001** [comment]
A differentiation of a "built-in" install vs an install you made yourself is kind of windows thinking. This isn't professional support, we're all hobbyists.
The lutris package and configuration used by default are unmodified from upstream, so lutris should be willing to help you. Generally speaking, projects support their own code, and issues that aren't directly caused by unofficial modifications (if those modifications exist). Especially since you aren't entitled to support anywhere, it's much more of a respect economy than anything. We're all just nerds playing with our really expensive calculators, at the end of the day

**Comment by DarkenLX** [comment]
> A differentiation of a "built-in" install vs an install you made yourself is kind of windows thinking. This isn't professional support, we're all hobbyists. The lutris package and configuration used by default are unmodified from upstream, so lutris should be willing to help you. Generally speaking, projects support their own code, and issues that aren't directly caused by unofficial modifications (if those modifications exist). Especially since you aren't entitled to support anywhere, it's much more of a respect economy than anything. We're all just nerds playing with our really expensive calculators, at the end of the day

Ah ok wasn't sure if it was modified compared to upstream ok i shall contact them on that then.
