### ISSUE TITLE
Within a Gamescope session, night mode is nonfunctional

### ISSUE THREAD

**Issue by jerbmega** [ublue-os/bazzite#58]
Night mode works properly within Plasma, but has no effect in Gamescope Big Picture.

**Comment by KyleGospo** [comment]
I suspect this is due to the name of the steam deck platform driver being different. SteamOS has it called jupiter or steamdeck_hwmon, and the one submitted upstream to the Linux kernel is just "steamdeck". Display controls are part of that driver.

We may need to rename the driver or build a patch for gamescope to use the name they gave upstream.

**Comment by KyleGospo** [comment]
This may be resolved by 1386380a484adc44f1443148748491a853c25f3a

**Comment by KyleGospo** [comment]
Closing this as a duplicate, it and https://github.com/ublue-os/bazzite/issues/62 are the same issue.

**Comment by TobiPeterG** [comment]
Hey there,

I'm currently working on an OS for the steam deck based on OpenSUSE. I face the same issue, does someone remeber what fixed it?
