### ISSUE TITLE
Stuck on ghcr.io/ublue-os/bazzite-deck:latest

### ISSUE THREAD

**Issue by Felzow47** [ublue-os/bazzite#637]
it never asked to connect to the internet 🤷 

![image](https://github.com/ublue-os/bazzite/assets/49567056/05bb8ce7-32f1-4baa-8544-a4312fc925df)

**Comment by KyleGospo** [comment]
Wait there, that means it's downloading and will jump up when the download is complete.

**Comment by Felzow47** [comment]
> Wait there, that means it's downloading and will jump up when the download is complete.

it never asked me to connect to the internet

**Comment by KyleGospo** [comment]
> > Wait there, that means it's downloading and will jump up when the download is complete.
> 
> it never asked me to connect to the internet
> 
> and I waited like 1 hour before coming to open a issue

Internet is required, you have to configure that in the installer. Please double check our install guide and the warnings at the top of the releases.

**Comment by Felzow47** [comment]
> > > Wait there, that means it's downloading and will jump up when the download is complete.
> > 
> > 
> > it never asked me to connect to the internet
> > and I waited like 1 hour before coming to open a issue
> 
> Internet is required, you have to configure that in the installer. Please double check our install guide and the warnings at the top of the releases.

No warning when I go into the installer I check all the thing and no warning so weird 
How heavy is the "ghcr.io/ublue-os/bazzite-deck:latest"? bc I don't have a really good speed internet, so it might be the problem if it really heavy

**Comment by ayo-x** [comment]
Hi. I've also experienced. For me it wasn't just the install that appeared as if stuck, but `ujust update` aswell. The issue here is that GitHub's ghcr.io is throttling the download speeds heavily. I was more that an hour into `ujust update` when I checked the network speed in the System Monitor app and was averaging below 1mb/s. I hit ctrl+c and the `rpm-ostree update` was bypassed and flatpaks began updating. Now the downloading speed was ~60mb/s. So I waited a couple of minutes and ran `ujust update` again and there was just a layer of 1.5gb left to download, but this time it was fast, over 50mb/s. This is not the first time this happened, I did stop the update process many times before for the same reason, but this time was the first time the speed shot up. Usually I just leave the updates for the next session when speeds are slow.
It could help if there were download speed, percentage and ETA indicators for the `rpm-ostree update` part of `ujust update` so it doesn't appear stuck. And in the installer also.
Maybe something could be fine from the ghcr.io side to improve the situation.
![Screenshot](https://github.com/ublue-os/bazzite/assets/35936440/57a0cde3-1856-4123-93ae-95122d5ed6d4)
