### ISSUE TITLE
Game mode UI - Appearance of Steam mouse cursor causes whole display color to change

### ISSUE THREAD

**Issue by brandflake11** [ublue-os/bazzite#655]
I am currently using bazzite-gnome-deck image on my custom built pc with these specs:

- OS: Fedora Linux 39.20240102.0 (Bazzite GNOME)
- Hardware: Micro-Star International Co., Ltd. MS-7D78
- Processor: AMD Ryzen™ 7 7700X × 16
- Memory: 32 GB
- Disk: 2.3 TB
- GPU: AMD Radeon™ RX 6800 XT, connected to non-hdr-compatible monitor over HDMI
- Kernel: Linux 6.6.8-200.fc39.x86_64

Whenever the game mode mouse cursor appears, the colors alter and turn into a light purple color, causing everything to be off. This happens in games that don't render their own mouse cursor as well. 

In the past, I was able to get around this by disabling color management in the developer options, but after an update, disabling color management causes the colors of the UI to become extremely dark. I had read enabling Force Composite may also help, but it does not appear to affect the issue.

It probably does not matter, but I used to use Chimeraos and did not have the same issue.

What might I be doing to cause this error? Thank you very much for your consideration and I will gladly paste any log information if needed.

**Comment by KyleGospo** [comment]
Try our :testing branch, this issue should go away.

**Comment by brandflake11** [comment]
I will try now and tell of the results, thank you.

**Comment by brandflake11** [comment]
The :testing branch has fixed the color issue when the mouse cursor appears. It is now consistent regardless of the mouse cursor's appearance. The color is still on the purple side, but I can tweak it somewhat with the gamemode Display UI color tweaker (it has vibrancy and temperature options). It is still just a tiny bit on the purple side compared to what I saw when using ChimeraOS. 

Does the game mode UI use a display profile for the steam deck's screen? Is this a possibility of why the colors look different?

**Comment by nicknamenamenick** [comment]
> I read the documentation and for bazzite and it says bazzite uses a color profile for the steam deck screen. Is this a possibility of why the colors look different? If so, is there a way to disable the color profile for the steam deck in the game mode UI?

You are referring to this line in the README:

> Color calibrated display profiles for matte and reflective Steam Deck screens included

Then I don't think that matters for this issue.

**Comment by brandflake11** [comment]
Thank you, I appreciate it. The way :testing is working is acceptable enough, as it is much better than before.

**Comment by brandflake11** [comment]
Okay, I have fixed the purple hue for my monitor and situation:

Steps:
1. Switched to Displayport instead of HDMI (finally got a good enough cable to do this with)
2. In the gamemode UI, go to Settings>Displays>Use Native Color Temperature to on

This is using the :stable branch as well, which is great. It disabled the color temperature adjustment feature, but now looks much more natural, and the vibrancy adjustment still works.

I'll go ahead and close this as it fixes my issues.

**Comment by Jean-PierreJ** [comment]
@brandflake11 This issue seems to have reappeared on the latest version of the Bazzite HTPC build. I have a fresh install (installed yesterday) and this is the case for both the Stable and Beta versions of Steam (I’m using Beta since I have the Steam Family Beta enabled, but it did this on Stable, as well).

Everything has a yellow tint to it when using a mouse but, when using a controller or keyboard it goes back to being more “white/bluish-white”. Visually it seems similar to when switching to Night Mode on the Steam Deck

I have Night Mode disabled and this still seems to be a problem. I did also try adjusting the Night Mode tint in Big Picture Mode to see of that changes anything but, even though you can see the visual changes while adjusting the slider, when moving the mouse it will go back to the same slightly-yellow tint; using a controller afterwards sets it back to the bluish white again.

OS Update Channel: Release Candidate
Steam Client Update Channel: Steam Deck Beta
OS Variant: bazzite-deck
OS Version: 40
OS Build: 9cc82a8
Kernel Version: 6.9.12-205.fsync.fc40.x86_64
BIOS Version: 3.06
Steam Version: 1725654351

**Comment by kuba-orlik** [comment]
@brandflake11 

> In the gamemode UI, go to Settings>Displays>Use Native Color Temperature to on

That did it for me, thanks!
