### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by SStoklosa23** [ublue-os/bazzite#661]
Hello, I tried installing bazzite but when I try to, I get this:
![20240107_164156.jpg](https://github.com/ublue-os/bazzite/assets/93952788/d87e5fff-3d04-4315-b0f3-c2394a0cd28f)

![20240107_164150.jpg](https://github.com/ublue-os/bazzite/assets/93952788/6b0d891c-8019-4aa9-98d1-8c35457905c0)

![20240107_164139.jpg](https://github.com/ublue-os/bazzite/assets/93952788/8e088052-e8cd-450e-9baf-55c50448af0a)

![20240107_164123.jpg](https://github.com/ublue-os/bazzite/assets/93952788/47a4936e-3b14-4608-abcc-7b154af90a63)

How do I fix it?

**Comment by m2Giles** [comment]
Are you doing a custom partitioning scheme?

**Comment by aderk** [comment]
I am running into the same problem.
HW: Ryzen + integrated CPU, ssd, UEFI boot, windows came pre-installed

I have tried the troubleshooting docs here (although this is for code -6 and I get exit code 1): https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_unable_to_install_fedora_silverblue_on_efi_systems

I think I've tried all the combinatorial options composed of:
1) wired/wireless
2) (Not) Adding root user
3) default / custom partitioning (with reformat EFI) / adding a new EFI partition (a la the above link)

This is the only real information I get:
<img width="521" alt="image" src="https://github.com/ublue-os/bazzite/assets/62039254/f7cf5d7a-dc38-4bd2-89d1-175ea009dd07">


@SStoklosa23, may I ask how you get to those logs? Is it on a virtual terminal e.g. ctrl+alt+f1?

**Comment by nathanapples** [comment]
+1 same issues for my install

**Comment by KyleGospo** [comment]
We now have a new offline installer that can be downloaded at https://bazzite.gg/#image-picker

Let us know if you have any issues with the new one :)

**Comment by TheComputerKid8712** [comment]
I am using this new offline installer and still am facing the same issue

**Comment by Haduken7331** [comment]
I have the same issue with the offline installer for the gnome version.

**Comment by njakes** [comment]
I can confirm that on my system, if I am reusing a /boot/efi for dual booting purposes the install will fail if there is a preexisting fedora folder in /boot/efi. If you delete that then the install will work as intended.

**Comment by ZZ0R0** [comment]
same error here, using custom partitioning with existing debian install and a ext4 shared partition, no windows, but same problem 
AMD Ryzen 5 5625U with Radeon Graphics

**Comment by Haduken7331** [comment]
This ostree installer error seems to be a known issue when trying to install fedora on top of fedora - which can easily be fixed by removing the fedora folder from the boot/efi partition.
Took me longer to realise there is already a video on this in the docs than necessary.
Here the link:
https://universal-blue.discourse.group/docs?topic=1146#generic-installer-error-workarounds-36

**Comment by ZZ0R0** [comment]
I have to check but i'm pretty sure i don't have a fedora folder neither a .efi file inside my efi partition, or at least there shouldn't be one because i've never installed fedora or based-on distros, furthermore i've cleaned my efi partition a few months ago, need to double check this but it would be problematic if the issue is the same with a debian efi folder because it would means that dual boot with debian is not possible (just speculating)
