### ISSUE TITLE
suggestion - adblocker

### ISSUE THREAD

**Issue by dkuku** [ublue-os/bazzite#667]
I just opened the hltb plugin in decky and there is lots of ads in the steam browser. any chance to add ublock or if maybe pi hole to the image?

**Comment by EyeCantCU** [comment]
Thank you for the suggestion!

I do not believe an ad blocker is something we should provide out of the box. I think this is something that largely.should be up to the user

There's lots of different ways to go about this (using the Ublock browser extension, using PiHole in a container, etc) and none are preferred over the other because they all have varying applications

Also, it's very likely that some methodologies may even lead to networking issues for some users
