### ISSUE TITLE
[Steam Deck] GAMESCOPE_OVERRIDE_REFRESH_RATE has no effect

### ISSUE THREAD

**Issue by erkexzcx** [ublue-os/bazzite#707]
I have Steam Deck (non-OLED, 512GB version) and BazziteOS (latest) with KDE/Plasma DE.

Adding `GAMESCOPE_OVERRIDE_REFRESH_RATE=40,70` to `/etc/environment` has no effect.

When I was using SteamOS, I was able to overclock the display to 70Hz, but I cannot do this with BazziteOS. On top of that, [the script](https://github.com/ryanrudolfoba/SteamDeck-RefreshRateUnlocker) that I've used in SteamOS does not work in BazziteOS as it is simply non-compatible.

Any advise?

**Comment by SerjTargarien** [comment]
Can confirm it doesn't work on my end. No solutions found for now.

**Comment by SilentViking** [comment]
This also has no effect for me. Using deck image on HTPC connected to LG OLED TV. 120hz works in desktop mode no problem, but gaming mode is locked to 60hz\60fps.
I added 'GAMESCOPE_OVERRIDE_REFRESH_RATE=60,70,80,90,100,110,120' to /etc/environment.

```sh
> echo $GAMESCOPE_OVERRIDE_REFRESH_RATE
> 60,70,80,90,100,110,120
```

**Comment by SilentViking** [comment]
Some combination of these changes got me to my desired refresh rate. I still thing there is some work needed to get 120 consistently? See notes about RDR2 below.

I  added this to /etc/environment, along with the aforementioned GAMESCOPE_OVERRIDE_REFRESH_RATE
> STEAM_DISPLAY_REFRESH_LIMITS=60,120

In Gaming Mode > Settings > Display > Disabled Universal Frame Rate Control (I forget the exact name. It's at the bottom. Might need to enable Developer Mode).

After these changes (and possibly a reboot) I was able to see two things in gaming mode performance overlay:
1. FPS Limit slider going to 120
2. Refresh Rate slider going to 120hz

I was using Red Dead Redemption II to test. However, for some reason that game is locked to 60hz, and I cannot change it in graphics settings. Maybe some other gamescope setting will help?
So I tested  random 2d game (Nartia Boy), and per gamescope performance overlay, i was hitting 120.

**Comment by WeslyG** [comment]
I'm using an i5 12400f + amd 7800xt and philips oled 807, the refresh mode can be 60 or 120 Hz, and everything is fine, but for some games, it would be very suitable to have 75 or 90Hz, I would like to control it. Because I balance between quality, performance and noise. And it would be great to have all the options to customize this. (for example, frame generator + refresh rate limitation, to minimize power consumption). I'm trying to set various environment variables. I'm reading the Refresh Rate Unlocker script and so far I can't add a new value to gamescore(

 I will be glad of any help

**Comment by lamiska** [comment]
GAMESCOPE_OVERRIDE_REFRESH_RATE and STEAM_DISPLAY_REFRESH_LIMITS seem to not work anymore and it is not possible to overclock SteamDeck LCD to 70Hz.
