### ISSUE TITLE
YAFTI description should indicate to reboot the system after finishing it.

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/bazzite#74]
I think something along these lines would work:
![image](https://github.com/ublue-os/bazzite/assets/121328689/4c6452bc-474b-4a5f-a84f-19032c49b144)

I was going to make a pull request, but I didn't exactly do that right last time and this is not a major priority right now.  This should try to warn the user in an event where setting up then going straight into Game Mode might cause YAFTI to appear if they return to Desktop Mode without rebooting after initial setup.

**Comment by KyleGospo** [comment]
My vote is we force a reboot, it's absolutely needed for kargs.

**Comment by tulilirockz** [comment]
Although forcing a reboot seems like a good idea, it would not be a very good UX, since idk, the user could be setting up their browsers, files, and suddenly: BAM their system restarts seemingly "out of the blue" (if they didn't see the message before that happened), like, yeah, I do know that Yafti is meant to be set-up at the first boot, but some people use it for just setting up their flatpaks or some other things post-first-boot...

**Comment by KyleGospo** [comment]
Could add it as an option at the end and stress why it's needed, but it's a guarantee people won't read and will run into problems.

**Comment by KyleGospo** [comment]
Another option would be to pop up a cancelable "your system will reboot in 5 minutes" prompt, but I would want to find an easy way to implement that that doesn't require a bunch of custom work.

**Comment by KyleGospo** [comment]
Fixed in https://github.com/ublue-os/bazzite/commit/8ee4ad223b66797520188fc7269c292c0cc7d08b
