### ISSUE TITLE
Can't add a password to the default user if I didnt set one during install

### ISSUE THREAD

**Issue by slrgt** [ublue-os/bazzite#906]
### Describe the bug

I installed bazzite on a usb and didnt add a password to the user when I was installing the OS. After using the OS I decided to keep using it but now I cant add a password to my default user. 

### What did you expect to happen?

When I go to the settings -> User section the settings are greyed out:

![image](https://github.com/ublue-os/bazzite/assets/114287507/9543cc37-8830-4d0f-a0a3-c5f73f33c4f1)

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
                   Digest: sha256:81850d0fb4899bfd721ac60ac37e1e4f1c2f5154190dc6bb957f8ae411378aaf
                  Version: 39.20240116.0 (2024-03-22T17:15:49Z)
          LayeredPackages: micro sunshine
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
                   Digest: sha256:178c01cc01532f0daf132806f1c6e67a01c81f518a3f9baf59d5605dd00f5e21
                  Version: 39.20240116.0 (2024-03-15T23:46:23Z)
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf" '
```

**Comment by HikariKnight** [comment]
this is caused by the installer even letting you set a blank password to begin with, which we do not have control over sadly.

Try opening terminal and type `passwd` to change it, keep in mind no characters will show up when you type in the password so make sure you type it in correctly.

if that does not work then you will have to re-install and follow the [installation guide](https://universal-blue.discourse.group/docs?topic=30)
