### ISSUE TITLE
I been wanted to ask this a long time now.

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#942]
When I'm installing a app or program through rpm-ostree it takes like 30 mins to install 1 application is that normal? Cause using dnf is like less than a min.

**Comment by nicknamenamenick** [comment]
Yes.  Using `rpm-ostree` should be the last resort for installing applications.  The packages layer to your image, so not only does it install the package but it also updates the image with this package layered on, so that takes a while.  The more packages layered also affect how long it takes for updates to finish.
