### ISSUE TITLE
Deck not turning off screen on Gnome and Gaming mode

### ISSUE THREAD

**Issue by Rafa12996** [ublue-os/bazzite#943]
### Describe the bug

After installing the OS, the device won't turn off the screen after meeting the time set on Gnome Settings. This also affects the time selected on Game Mode.

### What did you expect to happen?

Screen should be turned off to preserve power but it is not.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:bc18ac57e443ab2f930af7025d02fa9c4ac7d8fabd98d99047a7ce0e5bd99b9c
                  Version: 39.20240328.0 (2024-03-28T22:31:50Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:a2c014b946bb4fba5b112212bffb8ad8444d9cc7303c76c70128d3d12c956d07
                  Version: 39.20240328.0 (2024-03-28T22:31:50Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" '
```

### Hardware

Jupiter

**Comment by badlydrawnface** [comment]
This is due to (and you should have seen it the first time you entered Desktop Mode), that the Deck images do _not_ use GDM at the moment, hence why screen locking, nor screen turn off do not work, the Deck images mirror SteamOS by using SDDM. GDM support for the Deck images should be in the works in the future.

**Comment by telorand** [comment]
Do you mean that the screen isn't turning off or that the device isn't going into Sleep mode?

**Comment by Rafa12996** [comment]
> Do you mean that the screen isn't turning off or that the device isn't going into Sleep mode?

Screen doesn't go off until the suspend time is reached

**Comment by Rafa12996** [comment]
> This is due to (and you should have seen it the first time you entered Desktop Mode), that the Deck images do _not_ use GDM at the moment, hence why screen locking, nor does turning off the screen not work, the Deck images mirror SteamOS by using SDDM. GDM support for the Deck images should be in the works in the future.
> 
> As for Gaming mode, the screen doesn't turn off at all, it only dims or suspends.
> 
> If you have an OLED Steam Deck, just open a pitch black screen in full screen if you need to turn the pixels off.

I think this detail should be mentioned at download section. It's a huge deal breaker lost a basic feature. What about the KDE desktop, it works?

I was hoping to have a Gnome desktop finally on my deck. I'm using an LCD model, and I'm worried about damaging the screen by just downloading a big game because of the screen won't turn off while waiting

**Comment by Rafa12996** [comment]
Closed by mistake

**Comment by jpf91** [comment]
> As for Gaming mode, the screen doesn't turn off at all, it only dims or suspends.

@badlydrawnface Are you sure about this? I'm pretty sure the deck can turn off the screen in Steam OS. There's even a setting "Energy" => "Turn off screen" => "Turn off screen in mains operation after" in Gamemode, but it has no effect for me on Steam Deck with Bazzite (Gnome Edition). Why would there be this setting if this is not a feature?

I think it's actually the other way round: As this is supposed to happen automatically after some time, there is no way to **manually** turn off the screen. However, when waiting for large downloads, turning of the screen is the only reasonable option: I can't suspend, as otherwise Steam obviously won't download stuff. On the other hand, keeping the screen on 24/7 just to download, is a waste of energy and could even cause burn-in.

To be honest, I think this is quite a dealbreaker. I can understand that it might not be easy to debug, but if Bazzite does not even recognize this as an issue that needs to be fixed, I'll probably have to go back to Steam OS.

(The bug was also discussed here: https://universal-blue.discourse.group/t/deck-wont-turn-off-screen-by-time-set/990)
